refactor: Update scripts with better conventions

diff --git a/scripts/bash-helpers b/scripts/bash-helpers
--- a/scripts/bash-helpers
+++ b/scripts/bash-helpers
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-
+#
 ######################################################################
 # BASH HELPERS
 ######################################################################
@@ -209,3 +209,14 @@ die() {
 try() {
     "$@" || die "cannot $*"
 }
+
+
+# ----- Logging and Output ----- #
+
+err() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
+}
+# if ! do_something; then
+#   err "Unable to do_something"
+#   exit 1
+# fi
