chore: Rename files and delete clutter

diff --git a/scripts/mongo-backup b/scripts/mongo-backup
--- a/scripts/mongo-backup
+++ b/scripts/mongo-backup
@@ -1,4 +1,14 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+######################################################################
+# Deploy to Environment
+######################################################################
+
+# Fail script on command fail
+set -e
+
+# Include the bash helpers for color and formatting
+source bash-helpers
 
 # Make sure to:
 # 1) Name this file `backup.sh` and place it in /home/ubuntu
@@ -14,7 +24,7 @@ export HOME=/home/ubuntu/
 
 USER=ubuntu
 
-DATE=`/bin/date +%Y-%m-%d`
+DATE=$(/bin/date +%Y-%m-%d)
 
 HOST=localhost
 
@@ -38,6 +48,6 @@ echo "Backing up $HOST/$POSTGRES_DBNAME to s3://$BUCKET/ on $DATE";
 
 # Stream the backup to S3 because it is tiny
 # -Fc format is compressed by Postgres
-/usr/bin/pg_dump -Fc $POSTRES_DBNAME | aws s3 cp --storage-class STANDARD_IA - s3://$BUCKET/postgres/$DATE.dump
+/usr/bin/pg_dump -Fc $POSTGRES_DBNAME | aws s3 cp --storage-class STANDARD_IA - s3://$BUCKET/postgres/$DATE.dump
 
 echo "Finished Backups"
