build: Testing Github Actions MacOS

diff --git a/.github/workflows/python-cicd.yml b/.github/workflows/python-cicd.yml
--- a/.github/workflows/python-cicd.yml
+++ b/.github/workflows/python-cicd.yml
@@ -33,9 +33,13 @@ jobs:
       - name: MacOS start Docker
         if: matrix.os == 'macOS-latest'
         run: |
-          open -a /Applications/Docker.app --args --unattended --accept-license
-          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
-
+            brew install --cask docker
+            sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+            open -a /Applications/Docker.app --args --unattended --accept-license
+            echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+            while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+            shell: /bin/bash -e {0}
+            
       - name: Ubuntu installs
         if: matrix.os == 'ubuntu-latest'
         run: |
